<section class="my-3 container-md">
  <div class="table-responsive" style="min-width: 300px">
    <table class="table table-sm table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th scope="col">Tempo</th>
          <th scope="col">Segunda</th>
          <th scope="col">Terça</th>
          <th scope="col">Quarta</th>
          <th scope="col">Quinta</th>
          <th scope="col">Sexta</th>
          <th scope="col">Sábado</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">M1</th>
          <td></td>
          <td>IME04-10833</td>
          <td></td>
          <td>IME04-10833</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">M2</th>
          <td></td>
          <td>IME04-10833</td>
          <td></td>
          <td>IME04-10833</td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">M3</th>
          <td></td>
          <td></td>
          <td>IME04-10832</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">M4</th>
          <td></td>
          <td></td>
          <td>IME04-10832</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">M5</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>IME04-10832</td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">M6</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>IME04-10832</td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">T1</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">T2</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">T3</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">T4</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">T5</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">T6</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">N1</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">N2</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">N3</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">N4</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <th scope="row">N5</th>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
</section>
