<div class="container mb-3 mt-3">

  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasList">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title text-uerj-amarelo">Lista de Disciplinas</h5>
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="offcanvas"
      ></button>
    </div>
    <div class="offcanvas-body">
      <div
        class="d-flex flex-column align-items-stretch flex-shrink-0 bg-body-tertiary"
        style="width: 380px"
      >
        <div id="container-lista-discip" class="list-group list-group-flush border-bottom scrollarea">
          <!-- Item 1 -->
          <div class="list-group-item list-group-item-action py-3 lh-sm">
            <div>
              <a class="text-uerj-amarelo link-primary link-underline-opacity-0" href="#">
                <div
                  class="d-flex w-100 align-items-center justify-content-between"
                >
                  <strong class="mb-1 text-uerj-amarelo">IME04-10833</strong>
                  <div class="d-flex flex-column text-uerj-amarelo">
                    <small class="text-body-secondary">Ter M1 M2</small>
                    <small class="text-body-secondary">Qui M1 M2</small>
                  </div>
                </div>
                <div class="col-10 mb-1 small text-uerj-amarelo">
                  Análise e Projeto de Sistemas - Turma 1
                </div>
              </a>
            </div>
            <div class="col-10 mb-1 small text-uerj-amarelo">
              <a
                class="text-uerj-laranja"
                href="https://www.ementario.uerj.br/ementa.php?cdg_disciplina=10833"
                target="_blank"
                >Ementário</a
              >
            </div>
          </div>

          <!-- Item 2 -->
          <div class="list-group-item list-group-item-action py-3 lh-sm">
            <div>
              <a class="text-uerj-amarelo link-primary link-underline-opacity-0"" href="#">
                <div
                  class="d-flex w-100 align-items-center justify-content-between"
                >
                  <strong class="mb-1 text-uerj-amarelo">IME04-10832</strong>
                  <div class="d-flex flex-column text-uerj-amarelo">
                    <small class="text-body-secondary">Qua M3 M4</small>
                    <small class="text-body-secondary">Sex M5 M6</small>
                  </div>
                </div>
                <div class="col-10 mb-1 small text-uerj-amarelo">
                  Banco de Dados I - Turma 2
                </div>
              </a>
            </div>
            <div class="col-10 mb-1 small text-uerj-amarelo">
              <a
                class="text-uerj-laranja"
                href="https://www.ementario.uerj.br/ementa.php?cdg_disciplina=10832"
                target="_blank"
                >Ementário</a
              >
            </div>
          </div>

          <!-- Espaço para adicionar mais disciplinas -->
        </div>
      </div>
    </div>
  </div>
</div>